# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c8ed17e5487818dca7e0147dd5e5979c582a8cf480bd4a4c193334f5bb3a1cf109e7dc2f7ab01e81b288f0a973fc1d4d226d84064e7e882cb9aa9e9b646c612

test:
  secret_key_base: 2722b167bdad5f0cd352851f23a33d594eecdcc213eee956ccd14d5f87096ec2e4b9db28f34fe2d1565036080311bd24ec2d80bdb747735ab41fa42f9b87b1cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
